version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # 名前付きボリュームを使用
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro  # 同じボリュームを読み取り専用でマウント
    depends_on:
      - app

volumes:
  static_volume:  # 名前付きボリュームの定義