# Generated by Django 5.2.4 on 2025-10-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
